login: User_1_Login
password: 6f831d56c2
url_login: https://test-stand.gb.ru/gateway/login
url_posts: https://test-stand.gb.ru/api/posts
title: title_test_post
description: description_test_post
content: content_test_post